In [ ]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

## Update For Google Colab
# sys.path.append('/content/drive/MyDrive/')

## Update For Local
sys.path.append('/path/to/my/all_projects') ## e.g. sys.path.append('/data/sswar_files/0_PUBLISHED_CODES')

from SPEC2VEC.utils.gisqa_compute_updated import *
from SPEC2VEC.utils.spectograms_lib import *

/home/sswar/.local/lib/python3.10/site-packages/porespy/filters/_lt_methods.py:21: FutureWarning: `square` is deprecated since version 0.25 and will be removed in version 0.27. Use `skimage.morphology.footprint_rectangle` instead.
  strel = {2: {'min': disk(1), 'max': square(3)}, 3: {'min': ball(1), 'max': cube(3)}}
/home/sswar/.local/lib/python3.10/site-packages/porespy/filters/_lt_methods.py:21: FutureWarning: `cube` is deprecated since version 0.25 and will be removed in version 0.27. Use `skimage.morphology.footprint_rectangle` instead.
  strel = {2: {'min': disk(1), 'max': square(3)}, 3: {'min': ball(1), 'max': cube(3)}}
/home/sswar/.local/lib/python3.10/site-packages/porespy/metrics/_funcs.py:65: FutureWarning: `square` is deprecated since version 0.25 and will be removed in version 0.27. Use `skimage.morphology.footprint_rectangle` instead.
  strel = {2: {"min": disk(1), "max": square(3)}, 3: {"min": ball(1), "max": cube(3)}}
/home/sswar/.local/lib/python3.10/site-packages/porespy/metrics/_funcs.py:65: FutureWarning: `cube` is deprecated since version 0.25 and will be removed in version 0.27. Use `skimage.morphology.footprint_rectangle` instead.
  strel = {2: {"min": disk(1), "max": square(3)}, 3: {"min": ball(1), "max": cube(3)}}

#### 1D Time Series Example

In [ ]:
# Generate Signal
sr=100
t=5
x = np.linspace(0, t, sr*t)
y1 = np.sin(2 * np.pi * 35 * x) * np.exp(-((x - 4) ** 2) / (2 * 0.3 ** 2))
y2 = np.sin(2 * np.pi * 20 * x) * np.exp(-((x - 1) ** 2) / (2 * 0.3 ** 2))

giq = GISQAPipeline()
spec_pointwise_metrics_df = giq.compute_pointwise_metrics_from_spec(['example_1','example_2'], [y1, y2],
                                                                    is_hilbertize = 0,
                                                                    is_normalize_stat = 0,
                                                                    is_normalize_entropy = 0,
                                                                    is_best_features = 0,
                                                                    ordpydx = 4, antropydx = 4,
                                                                    metrics_list=None, hilbert_locs=None)

spec_pointwise_metrics_df

1 number of row processed

,permutation_entropy_antropy,spectral_entropy_antropy,svd_entropy_antropy,approximate_entropy_antropy,sample_entropy_antropy,hjorth_mobility_antropy,hjorth_complexity_antropy,num_zerocross_antropy,petrosian_fd_antropy,katz_fd_antropy,higuchi_fd_antropy,detrended_fluctuation_antropy,normalized_permutation_entropy_ordpy,statistical_complexity_entropy_ordpy,fisher_shannon_ordpy,global_node_entropy_ordpy,missing_links_ordpy,missing_patterns_ordpy,renyi_complexity_entropy_short_ordpy,renyi_stat_complexity_short_ordpy,renyi_complexity_entropy_long_ordpy,renyi_stat_complexity_long_ordpy,renyi_complexity_entropy_3_ordpy,renyi_stat_complexity_3_ordpy,tsallis_complexity_entropy_short_ordpy,tsallis_stat_complexity_short_ordpy,tsallis_complexity_entropy_long_ordpy,tsallis_stat_complexity_long_ordpy,weighted_permutation_entropy_ordpy,0_Absolute energy,0_Average power,0_ECDF Percentile_0,0_ECDF Percentile_1,0_ECDF Percentile_2,0_Histogram mode,0_Interquartile range,0_Kurtosis,0_Lempel-Ziv complexity,0_Mean,0_Mean absolute deviation,0_Median,0_Median absolute deviation,0_Peak to peak distance,0_Root mean square,0_Signal distance,0_Skewness,0_Standard deviation,0_Variance,75th_percentile,25th_percentile,label
0,0.792536,0.412137,0.564544,0.029564,0.005782,1.785704,1.000074,349,1.041366,3.538555,2.005596,0.034079,0.792536,0.236615,0.248709,0.583716,0.645833,0.25,0.842230,0.206497,0.759082,0.269653,0.709487,0.346495,0.721382,0.194975,0.880374,0.281168,2.209193,26.533602,0.053174,-1.710540e-06,-5.771939e-39,0.000002,0.012786,0.000003,6.993568,0.140,-0.000002,0.095531,-2.885969e-39,0.000002,1.950790,0.230363,531.710387,0.000026,0.230363,0.053067,0.000002,-1.042313e-06,example_1
1,0.750269,0.312060,0.573292,0.025855,0.005889,1.178859,1.000527,200,1.024467,2.836126,2.295242,0.119148,0.750269,0.294838,0.548885,0.178862,0.822917,0.50,0.760458,0.281646,0.743814,0.326340,0.730210,0.411391,0.602230,0.239635,0.871137,0.348587,2.015677,26.533602,0.053174,-3.610299e-10,0.000000e+00,0.000314,0.002453,0.000324,6.993568,0.132,0.000005,0.096641,4.889597e-54,0.000001,1.842514,0.230363,515.010569,-0.000069,0.230363,0.053067,0.000324,-3.195771e-10,example_2

#### 2D Input (TFR) Example

In [47]:
f1, t1, stft1 = stft_basic_spectogram(y1,sr,64,0.5,"hann",0,50,
                                     max_normalize=False, powerlog=False,vmin_percentile=2, vmax_percentile=98)
f1, t1, stft2 = stft_basic_spectogram(y2,sr,64,0.5,"hann",0,50,
                                     max_normalize=False, powerlog=False,vmin_percentile=2, vmax_percentile=98)
#plt.pcolormesh(t1,f1,stft1); plt.pcolormesh(t1,f1,stft2)

metrics_to_compute = ['permutation_entropy_antropy', 'spectral_entropy_antropy', 'svd_entropy_antropy', 'detrended_fluctuation_antropy']

giq = GISQAPipeline()
spec_pointwise_metrics_df = giq.compute_pointwise_metrics_from_spec(['example_1','example_2'], [stft1, stft2],
                                                                    is_hilbertize = 1,
                                                                    is_normalize_stat = 0,
                                                                    is_normalize_entropy = 0,
                                                                    is_best_features = 0,
                                                                    ordpydx = 5, antropydx = 5,
                                                                    metrics_list=metrics_to_compute, 
                                                                    hilbert_locs=None)

spec_pointwise_metrics_df

1 number of row processed

,permutation_entropy_antropy,spectral_entropy_antropy,svd_entropy_antropy,detrended_fluctuation_antropy,label
0,0.763724,0.675432,0.764166,1.181220,example_1
1,0.788578,0.732292,0.849093,1.161543,example_2